BugTracker/Models/TicketAttachment.cs
using BugTracker.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BugTracker.Models
{
    public class TicketAttachment
    {
        public int Id { get; set; }
        public int TicketId { get; set; }
        public string Description { get; set; }
        public DateTimeOffset Created { get; set; }
        //public DateTime Updated { get; set; }
        public string UserId { get; set; }
        public string FileUrl { get; set; }

        public virtual Ticket Ticket { get; set; }
        public virtual ApplicationUser User { get; set; }
    }
}

BugTracker/Controllers/TicketAttachmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using BugTracker.Models;
using Microsoft.AspNet.Identity;

namespace BugTracker.Controllers
{
    public class TicketAttachmentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: TicketAttachments
        public ActionResult Index()
        {
            var ticketAttachments = db.TicketAttachments.Include(t => t.Ticket).Include(t => t.User);
            return View(ticketAttachments.ToList());
        }

        // GET: TicketAttachments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TicketAttachment ticketAttachment = db.TicketAttachments.Find(id);
            if (ticketAttachment == null)
            {
                return HttpNotFound();
            }
            return View(ticketAttachment);
        }

        // GET: TicketAttachments/Create
        public ActionResult Create(int ticketId)
        {

            TicketAttachment model = new TicketAttachment();
            model.TicketId = ticketId;
            model.Ticket = db.Tickets.Find(ticketId);
            return View(model);
            //ViewBag.TicketId = new SelectList(db.Tickets, "Id", "Title");
            //ViewBag.UserId = new SelectList(db.Users, "Id", "Email");
            //return View();
        }

        // POST: TicketAttachments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,TicketId,Description,Created,UserId,FileUrl")] TicketAttachment ticketAttachment, HttpPostedFileBase image)
        {
            var FullName = User.Identity.GetUserId();
            Ticket ticket = db.Tickets.Find(ticketAttachment.TicketId);
            ApplicationUser user = db.Users.Find(ticket.AssignedToUserId);

            if (ModelState.IsValid)

            {
                //{
                //    db.TicketAttachments.Add(ticketAttachment);
                //    db.SaveChanges();
                //    return RedirectToAction("Index");
                //}

                if (ImageUploadViewModel.IsWebFriendlyImage(image))
                {
                    var fileName = Path.GetFileName(image.FileName);
                    image.SaveAs(Path.Combine(Server.MapPath("~/Uploads/"), fileName));
                    ticketAttachment.FileUrl = "/Uploads/" + fileName;

                    ticketAttachment.UserId = FullName;
                    ticketAttachment.Created = DateTimeOffset.Now;
                    db.TicketAttachments.Add(ticketAttachment);
                    db.SaveChanges();
                    //return RedirectToAction("Index");

                }


                var callbackUrl = Url.Action("Details", "Tickets", new { id = ticketAttachment.TicketId }, protocol: Request.Url.Scheme);
                try
                {
                    EmailService ems = new EmailService();
                    IdentityMessage msg = new IdentityMessage();
                    msg.Body = "A new attachment has been added." + Environment.NewLine + "Please click the following link to view the details" + "<a href=\"" + callbackUrl + "\"> NEW TICKET</a>";
                    msg.Destination = user.Email;
                    msg.Subject = "Attachment Added";
                    //msg.Subject = "Assigned Ticket";

                    ems.Send(msg);
                    //await ems.SendMailAsync(msg);
                }
                catch (Exception ex)
                {
                    Task.FromResult(0);
                    //await Task.FromResult(0);
                }
                return RedirectToAction("Details", "Tickets", new { id = ticketAttachment.TicketId });
            }


            ViewBag.TicketId = new SelectList(db.Tickets, "Id", "Title", ticketAttachment.TicketId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", ticketAttachment.UserId);
            return View(ticketAttachment);

        }

        // GET: TicketAttachments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TicketAttachment ticketAttachment = db.TicketAttachments.Find(id);
            if (ticketAttachment == null)
            {
                return HttpNotFound();
            }
            ViewBag.TicketId = new SelectList(db.Tickets, "Id", "Title", ticketAttachment.TicketId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", ticketAttachment.UserId);
            return View(ticketAttachment);
        }

        // POST: TicketAttachments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,TicketId,Description,Created,UserId,FileUrl")] TicketAttachment ticketAttachment, HttpPostedFileBase image)
        {
            var FullName = User.Identity.GetUserId();

            if (ModelState.IsValid)
            {
                //db.Entry(ticketAttachment).State = EntityState.Modified;
                //db.SaveChanges();
                //return RedirectToAction("Index");
            }
            if (ImageUploadViewModel.IsWebFriendlyImage(image))
            {
                var fileName = Path.GetFileName(image.FileName);
                image.SaveAs(Path.Combine(Server.MapPath("~/Uploads/"), fileName));
                ticketAttachment.FileUrl = "/Uploads/" + fileName;

                //ticketAttachment.Updated = DateTime.Now;
                ticketAttachment.UserId = FullName;
                ticketAttachment.Created = DateTimeOffset.Now;
                db.Entry(ticketAttachment).State = EntityState.Modified;
                db.SaveChanges();
                //return RedirectToAction("Index");
                return RedirectToAction("Details", "Tickets", new { id = ticketAttachment.TicketId });
            }

            ViewBag.TicketId = new SelectList(db.Tickets, "Id", "Title", ticketAttachment.TicketId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", ticketAttachment.UserId);
            return View(ticketAttachment);
        }

        // GET: TicketAttachments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TicketAttachment ticketAttachment = db.TicketAttachments.Find(id);
            if (ticketAttachment == null)
            {
                return HttpNotFound();
            }
            return View(ticketAttachment);
        }

        // POST: TicketAttachments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TicketAttachment ticketAttachment = db.TicketAttachments.Find(id);
            db.TicketAttachments.Remove(ticketAttachment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BugTracker/Views/TicketAttachments/Create.cshtml
@model BugTracker.Models.TicketAttachment

@{
    ViewBag.Title = "Create";
}
<div class="align-center" style="font-style:oblique; padding-bottom:40px">
    <h4>Create Ticket Attachments</h4>
</div>

    @using (Html.BeginForm("Create", "TicketAttachments", FormMethod.Post, new { enctype = "Multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

<div class="form-horizontal">
    @*<h4>Ticket Attachment</h4>*@
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group" style="padding-bottom:40px">
        @Html.LabelFor(model => model.TicketId, "Ticket Title", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Ticket.Title)
            @Html.HiddenFor(model => model.TicketId)
            @*@Html.DropDownList("TicketId", null, htmlAttributes: new { @class = "form-control" })*@
            @Html.ValidationMessageFor(model => model.TicketId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" style="padding-bottom:40px">
        @Html.LabelFor(model => model.Description, "File Description", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
            </div>
        </div>*@

    @*<div class="form-group" style="padding-bottom:50px">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group" style="padding-bottom:40px">
        @Html.LabelFor(model => model.FileUrl, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input name="image" type="file" class="form-control" id="fileUpload" />
            @*@Html.EditorFor(model => model.FileUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileUrl, "", new { @class = "text-danger" })*@
        </div>
    </div>

    @*<div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>*@

    <div class="form-group" style="padding-bottom:30px">
        <div class="col-md-offset-4 col-md-4">
            <input type="submit" value="Create Attachment" class="btn btn-block btn-primary" />
        </div>
    </div>
</div>
    }

    
        <div>
            @Html.ActionLink("Back to Ticket Details", "Details", "Tickets", new { id = Model.TicketId }, new { @class = "btn btn-lg btn-success" })
        </div>
       


    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

BugTracker/Views/TicketAttachments/Delete.cshtml
@model BugTracker.Models.TicketAttachment

@{
    ViewBag.Title = "Delete";
}

<div style="float:left; padding-bottom:30px; padding-right:15px">
    <h3>Are you sure you want to delete this ticket attachment?  @*<a href="@Url.Action("Delete",new { id = Model.Id })" class="btn btn-xs btn-info"><i class="fa fa-trash"></i></a>*@</h3>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color" style="margin-top:22px">
        <input type="submit" value="Delete" class="btn btn-primary" /> 
        
    </div>
}
@*<h3>Are you sure you want to delete this?</h3>*@
<div>

    <div class="container-fluid">
        <div class="panel panel-default col-sm-8">
            <div class="panel-body">
                <p>
                    <label>Ticket Title :</label>
                    @Html.DisplayFor(model => model.Ticket.Title)
                </p>
                </br>
                <p>
                    <label>Attachment created date: </label>
                    @Model.Created.ToString("MMM dd yyyy")
                    @*@Html.DisplayFor(model => model.Created)*@
                </p>
                </br>
                <p>
                    <label>File Description: </label>
                    @Html.DisplayFor(model => model.Description)

                </p>
                </br>
                <p>
                    <label>File created by: </label>
                    @Html.DisplayFor(model => model.User.Email)
                </p>
                </br>
                <p>
                    <label>File</label>
                    @Html.DisplayFor(model => model.FileUrl)
                </p>
            </div>
        </div>
    </div>


    @*<h4>TicketAttachment</h4>
        <hr />*@
    @*<dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Ticket.Title)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Ticket.Title)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.User.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.User.Email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Created)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Created)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.FileUrl)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FileUrl)
            </dd>

        </dl>*@
    <div style="margin-left:20px">
        <p>
            
                @Html.ActionLink("Back to Ticket Details", "Details", "Tickets", new { id = Model.TicketId }, new { @class = "btn btn-lg btn-success" })
           
        </p>
    </div>

    @*@using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }*@
</div>

BugTracker/Views/TicketAttachments/Details.cshtml
@model BugTracker.Models.TicketAttachment

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>TicketAttachment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ticket.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ticket.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileUrl)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BugTracker/Views/TicketAttachments/Edit.cshtml
@model BugTracker.Models.TicketAttachment

@{
    ViewBag.Title = "Edit";
}

<div class="align-center" style="font-style:oblique; padding-bottom:30px">
    <h3>Edit Ticket Attachments</h3>
    </div>


    @using (Html.BeginForm("Edit", "TicketAttachments", FormMethod.Post, new { enctype = "Multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

<div class="form-horizontal">
    @*<h4>TicketAttachment</h4>
        <hr />*@
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.Created)

    <div class="form-group" style="padding-bottom:30px">
        @Html.LabelFor(model => model.TicketId, "Ticket Title", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Ticket.Title)
            @Html.HiddenFor(model => model.TicketId)
            @*@Html.DropDownList("TicketId", null, htmlAttributes: new { @class = "form-control" })*@
            @Html.ValidationMessageFor(model => model.TicketId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" style="padding-bottom:30px">
        @Html.LabelFor(model => model.Description, "File Description", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group" style="padding-bottom:30px">
        @Html.LabelFor(model => model.UserId, "Edited by", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.User.FullName)
            @Html.HiddenFor(model => model.UserId)
            @*@Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })*@
            @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" style="padding-bottom:40px">
        @Html.LabelFor(model => model.FileUrl, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input name="image" type="file" class="form-control" id="fileUpload" />
            @*@Html.EditorFor(model => model.FileUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileUrl, "", new { @class = "text-danger" })*@
        </div>
    </div>

    @*<div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>*@

    <div class="form-group" style="padding-bottom:30px">
        <div class="col-md-offset-4 col-md-4">
            <input type="submit" value="Save" class="btn btn-block btn-primary" />
        </div>
    </div>
</div>
    }

<div>
    @Html.ActionLink("Back to Ticket Details", "Details", "Tickets", new { id = Model.TicketId }, new { @class = "btn btn-lg btn-success" })
</div>
    

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

BugTracker/Views/TicketAttachments/Index.cshtml
@model IEnumerable<BugTracker.Models.TicketAttachment>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table id="ticketattachment" class="table">
    <thead>
        @*@foreach (var item in Model)
            {
                <div class="col-12 col-md-3 col-lg-4">
                    <article class="card">
                        @if (item.MediaURL != null)
                        {
                            <img class="card-img-top" src="@Url.Content(item.MediaURL)" style="width:340px; height:300px" />
                        }*@
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Ticket.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Created)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FileUrl)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Ticket.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.User.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Created)
                </td>
                <td>
                    @if (item.FileUrl != null)
                    {
                        <a href="@Url.Content(item.FileUrl)">
                            <img src="~/Assets/images/389801.svg" style="height:20px; width:30px"/> @*<img src="~/"*@
                        </a>
                        @*<image class="image-responsive" src="@Url.Content(item.FileUrl)" style="width:50px; height:50px" />*@
                    }
                    @*@Html.DisplayFor(modelItem => item.FileUrl)*@
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @*@Html.ActionLink("Details", "Details", new { id = item.Id }) |*@
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts{
    <script>
        $('#ticketattachment').DataTable();
    </script>}
@*<script>
        $(document).ready(function () {
            $('button.btn.dropdown-toggle.btn-default').hide();
        });
    </script>*@